# Generated by Django 5.2.8 on 2025-11-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insightx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("source_channel", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
