# Generated by Django 5.2.8 on 2025-11-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insightx", "0002_userprofileanalytics"),
        ("jobs", "0002_jobinteraction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobskill",
            name="job",
        ),
        migrations.RemoveField(
            model_name="userinteraction",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobskill",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="userinteraction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="user",
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="district",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="education_level",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="source_channel",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("session_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("job_view", "Job View"),
                            ("job_apply", "Job Apply"),
                            ("chatbot_message", "Chatbot Message"),
                            ("profile_update", "Profile Update"),
                            ("skill_gap_run", "Skill Gap Run"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path like /jobs, /analytics, etc.",
                        max_length=255,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="JobSkill",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="UserInteraction",
        ),
        migrations.DeleteModel(
            name="UserSkill",
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["user_id", "event_type"], name="insightx_an_user_id_cfa0be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="insightx_an_event_t_ce9e37_idx",
            ),
        ),
    ]
