# Generated by Django 5.2.5 on 2025-11-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insightx", "0003_remove_jobskill_job_remove_userinteraction_job_and_more"),
        ("jobs", "0003_delete_applicationevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("job_view", "Job View"),
                    ("job_apply", "Job Apply"),
                    ("chatbot_message", "Chatbot Message"),
                    ("profile_update", "Profile Update"),
                    ("skill_gap_run", "Skill Gap Run"),
                    ("acquisition", "Acquisition"),
                    ("session_duration", "Session Duration"),
                    ("scroll_depth", "Scroll Depth"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="source_channel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Where the user first saw PGRKAM (WhatsApp, Facebook, College, etc.)",
                max_length=120,
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["page", "created_at"], name="insightx_an_page_5b57a5_idx"
            ),
        ),
    ]
