# Generated by Django 5.2.5 on 2025-11-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insightx", "0004_alter_analyticsevent_event_type_and_more"),
        ("jobs", "0003_delete_applicationevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=20,
                    ),
                ),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("match_ratio", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="insightx_an_user_id_cfa0be_idx",
        ),
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="insightx_an_event_t_ce9e37_idx",
        ),
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="insightx_an_page_5b57a5_idx",
        ),
        migrations.RemoveField(
            model_name="userprofileanalytics",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="page",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="education_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="gender",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="source_channel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="user_id",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="joboutcome",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.job",
            ),
        ),
    ]
