# Generated by Django 5.2.8 on 2025-11-30 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insightx", "0005_joboutcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="page",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="session_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="education_level",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofileanalytics",
            name="source_channel",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
