# Generated by Django 5.2.5 on 2025-11-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobinteraction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationEvent",
        ),
    ]
