# Generated by Django 5.2.5 on 2025-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_delete_applicationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="qualifications",
            field=models.TextField(blank=True),
        ),
    ]
