# Generated by Django 5.2.5 on 2025-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_description_job_qualifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="min_experience",
        ),
        migrations.RemoveField(
            model_name="job",
            name="posted_at",
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="qualifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
